### ISSUE TITLE
Ability to add a description of what the variant is for (not the variantDescription)

### ISSUE THREAD

**Issue by noah-severyn** [memo33/sc4pac-actions#2]
I think it be a good idea to add one extra bit of information to the variant where we can explain what the variant is for, as opposed to just explaining the individual *values* of the variant. This would not be relevant for all (or maybe most?) variants, but for some I think it could be very nice. Here's the scenario that gave me this idea:

I was installing something that required sfbt:essentials as a dependency, and was met with this prompt to make a choice:

![Image](https://github.com/user-attachments/assets/61160e0b-cc90-4af1-a92d-fa01780fd50e)

First, I don't necessarily know what sfbt:essentials is as I didn't call to install it myself. Secondly, and what this issue is about, I especially don't know what the [sfbt:essentials:tree-family](https://github.com/memo33/sc4pac/blob/main/src/yaml/sfbt/essentials.yaml#L11) variant does. At first I thought it was something like [this](https://community.simtropolis.com/files/file/16098-bsc-sfbt-street-tree-mod/) that would replace all trees across all lots. However, a deeper reading of the readme (which ironically wouldn't be included with sc4pac), revealed that it only replaces/changes the trees on lots that use certain prop families in sfbt:essentials. It would be nice if we were able to say something like the following to be able to give users some idea about what will happen when they pick one of the variant choices.

> sfbt:essentials:tree-family - Choose a type of trees to appear on custom lots which support this feature

This option is well enough described in the [package description](https://github.com/memo33/sc4pac/blob/main/src/yaml/sfbt/essentials.yaml#L77), but that doesn't appear if you're installing this package implicitly. Hopefully this is the right repo to post this request to. Let me know your thoughts.

**Comment by memo33** [comment]
Yes, thanks for bringing this up. I wanted to add support for this for a while now.

My proposal is to switch to this format:
```yaml
variantInfo:
  - label: nightmode
    description: ""         # new, optional
    values:                 # optional
      - value: standard
        description: ""
        default: true       # new, optional
      - value: dark
        description: ""
  - label: driveside
    description: ""
    values:
      - value: right
        description: ""
      - value: left
        description: ""
```

This new `variantInfo` field would take the place of the earlier `variantDescriptions` (which would be deprecated, but kept for backward-compatibility).

This would add support for adding a `description` to the variant label itself, a markdown-formatted text field that is displayed before all the options.

Additionally, this adds an optional `default` field. I think I would still show the selection dialog, but this allows to define a pre-selected default value.

Does this format cover everything we need? What are your thoughts? The rendering format of the variant selection dialog could even be made more granular if we add fields like `title`, `question`, `pretext`, `posttext` for each variant label, but I don't want to overcomplicate it.

CC @zasco @sebamarynissen
